spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'encheres'
    password: 'encheres'
    url: jdbc:postgresql://localhost:5432/encheres?charSet=UTF-8&prepareThreshold=0
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /encheres/api
  error:
    include-message: always

security:
  jwt:
    token:
      secret-key: my-secret-key
      expiration: 300_000 # 5 min
    refresh-token:
      expiration: 86_400_000 # 1 jour